<?php
$ffield_6_xiaoshuo_pic_0 = array (
  'fid' => '25',
  'ename' => 'xiaoshuo_pic',
  'cname' => '小说图片',
  'chid' => '6',
  'issystem' => '0',
  'available' => '1',
  'isfunc' => '0',
  'func' => '',
  'innertext' => '',
  'fromcode' => '0',
  'length' => '0',
  'datatype' => 'image',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '1',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '上传小说封面图片',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>