<?php
$gmission27_0 = array (
  'gsid' => '27',
  'cname' => '清风历史小说',
  'gmid' => '6',
  'sonid' => '28',
  'pid' => '0',
  'mcharset' => 'gbk',
  'timeout' => '5',
  'mcookies' => '',
  'umode' => '0',
  'uurls' => '',
  'uregular' => 'http://book.qingfo.com/modules/article/articlelist.php?class=5&page=(*)',
  'ufromnum' => '1',
  'utonum' => '1',
  'ufrompage' => '0',
  'udesc' => '0',
  'uinclude' => '',
  'uforbid' => '',
  'uregion' => '<th width="20%">文章名称</th>(*)</table>',
  'uspilit' => '</tr>',
  'uurltag' => '<td class="odd"><a href="(*)">',
  'utitletag' => '<td class="odd"><a href="(?)">(*)</a></td>',
  'uurltag1' => '<a class="btnlink" href="(*)">',
  'uinclude1' => '',
  'uforbid1' => '',
  'uurltag2' => '',
  'uinclude2' => '',
  'uforbid2' => '',
  'mpfield' => '',
  'mpmode' => '0',
  'mptag' => '',
  'mpinclude' => '',
  'mpforbid' => '',
  'fsettings' => 
  array (
    'subject' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '<span style="font-size:16px; font-weight: bold; line-height: 150%">(*)</span>',
      'fromreplace' => '',
      'toreplace' => '',
      'rpid' => '0',
      'jumpfile' => '',
      'clearhtml' => '12',
    ),
    'author' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '作    者：</td>',
      'fromreplace' => '',
      'toreplace' => '',
      'rpid' => '0',
      'jumpfile' => '',
      'clearhtml' => '',
    ),
    'thumb' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '<td width="20%" align="center" valign="top" style="font-size:13px">
		<img src="(*)"',
      'fromreplace' => '',
      'toreplace' => '',
      'rpid' => '1',
      'jumpfile' => '',
      'clearhtml' => '',
    ),
    'content' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '内容简介：</span>(*)<span class="hottext">',
      'fromreplace' => '　',
      'toreplace' => '',
      'rpid' => '0',
      'jumpfile' => '',
      'clearhtml' => '2,12',
    ),
  ),
  'dvalues' => 
  array (
    'musts' => 'subject',
    'autoabstract' => '1',
    'caid' => '6',
    'source' => '',
    'keywords' => '',
    'ccid1' => '0',
    'ccid2' => '0',
    'ccid3' => '0',
    'ccid4' => '0',
    'ccid5' => '0',
    'ccid7' => '0',
    'ccid6' => '0',
    'autothumb' => '0',
  ),
  'sid' => '0',
) ;
?>