<?php
$catalog1_0 = array (
  'caid' => '1',
  'sid' => '0',
  'level' => '0',
  'pid' => '0',
  'title' => 'ÄÐÆµ',
  'vieworder' => '0',
  'trueorder' => '0',
  'chids' => '4,1',
  'mchids' => '',
  'isframe' => '1',
  'dirname' => 'xiaoshuo',
  'smallsite' => '',
  'apmid' => '2',
  'crpmid' => '0',
  'rpmid' => '0',
  'dpmid' => '1',
  'allowsale' => '1',
  'allowfsale' => '1',
  'taxcp' => '',
  'awardcp' => '',
  'ftaxcp' => '',
  'customurl' => '',
  'clicks' => '0',
  'archives' => '0',
  'indextpl' => 'column_index.html',
  'listtpl' => 'column_other_1.html',
  'bktpl' => '',
) ;
?>