<?php
$murl3_0 = array (
  'muid' => '3',
  'cname' => '专辑管理',
  'remark' => '专辑管理',
  'uclass' => 'archives',
  'issys' => '0',
  'available' => '1',
  'vieworder' => '0',
  'url' => '?action=archives&nmuid=3',
  'setting' => 
  array (
    'checked' => '-1',
    'valid' => '-1',
    'sids' => '',
    'caids' => '13',
    'chids' => '',
    'filters' => 'catalog,check',
    'lists' => 'catalog,uclass,adddate,view,admin',
    'operates' => 'delete',
    'imuids' => '1,3,4',
    'ccids1' => '',
    'ccids2' => '',
    'ccids3' => '',
    'ccids4' => '',
    'ccids5' => '',
    'ccids6' => '',
    'ccids7' => '',
  ),
  'tplname' => '',
  'onlyview' => '0',
  'isbk' => '0',
  'mtitle' => '',
  'otitle' => '',
  'guide' => '',
) ;
?>