<?php
$permissions_0 = array (
  1 => 
  array (
    'pmid' => '1',
    'cname' => '所有会员权限',
    'aread' => '1',
    'cread' => '1',
    'aadd' => '0',
    'down' => '1',
    'fadd' => '0',
    'cuadd' => '1',
    'menu' => '0',
    'field' => '0',
    'vieworder' => '0',
    'ugids' => '-1',
    'fugids' => '',
  ),
  2 => 
  array (
    'pmid' => '2',
    'cname' => '作家会员权限',
    'aread' => '1',
    'cread' => '1',
    'aadd' => '1',
    'down' => '1',
    'fadd' => '0',
    'cuadd' => '1',
    'menu' => '1',
    'field' => '0',
    'vieworder' => '0',
    'ugids' => '12,21',
    'fugids' => '',
  ),
  3 => 
  array (
    'pmid' => '3',
    'cname' => '文档发布权限',
    'aread' => '0',
    'cread' => '0',
    'aadd' => '1',
    'down' => '0',
    'fadd' => '0',
    'cuadd' => '0',
    'menu' => '0',
    'field' => '0',
    'vieworder' => '0',
    'ugids' => '14,12,13',
    'fugids' => '',
  ),
  4 => 
  array (
    'pmid' => '4',
    'cname' => '日常管理员权限',
    'aread' => '1',
    'cread' => '1',
    'aadd' => '1',
    'down' => '1',
    'fadd' => '1',
    'cuadd' => '1',
    'menu' => '1',
    'field' => '1',
    'vieworder' => '0',
    'ugids' => '14',
    'fugids' => '',
  ),
  5 => 
  array (
    'pmid' => '5',
    'cname' => '专辑发布权限',
    'aread' => '0',
    'cread' => '0',
    'aadd' => '1',
    'down' => '0',
    'fadd' => '0',
    'cuadd' => '0',
    'menu' => '1',
    'field' => '0',
    'vieworder' => '0',
    'ugids' => '14,13',
    'fugids' => '',
  ),
) ;
?>