<?php
$ffield_9_subject_0 = array (
  'fid' => '35',
  'ename' => 'subject',
  'cname' => '信息标题',
  'chid' => '9',
  'issystem' => '1',
  'available' => '1',
  'isfunc' => '0',
  'func' => '',
  'innertext' => '',
  'fromcode' => '0',
  'length' => '255',
  'datatype' => 'text',
  'notnull' => '1',
  'nohtml' => '0',
  'mlimit' => '0',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>