<?php
$mfield_1_photo_0 = array (
  'mfid' => '18',
  'cname' => '头像',
  'ename' => 'photo',
  'mchid' => '1',
  'issystem' => '0',
  'available' => '1',
  'iscustom' => '1',
  'mcommon' => '0',
  'isfunc' => '0',
  'func' => '',
  'tbl' => 'custom',
  'innertext' => '',
  'fromcode' => '0',
  'issearch' => '0',
  'length' => '0',
  'datatype' => 'image',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => '0',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '以66px * 66px的图片为宜',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>