<?php
$mfield_1_password_0 = array (
  'mfid' => '11',
  'cname' => 'УмТы1',
  'ename' => 'password',
  'mchid' => '1',
  'issystem' => '1',
  'available' => '1',
  'iscustom' => '0',
  'mcommon' => '1',
  'isfunc' => '0',
  'func' => '',
  'tbl' => 'main',
  'innertext' => '',
  'fromcode' => '0',
  'issearch' => '0',
  'length' => '15',
  'datatype' => 'text',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => 'notnull',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '2',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>