<?php
$ffield_4_advimg_0 = array (
  'fid' => '15',
  'ename' => 'advimg',
  'cname' => '¹ã¸æÍ¼Æ¬',
  'chid' => '4',
  'issystem' => '0',
  'available' => '1',
  'isfunc' => '0',
  'func' => '',
  'innertext' => '',
  'fromcode' => '0',
  'length' => '0',
  'datatype' => 'image',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>