<?php
$ffield_3_content_0 = array (
  'fid' => '13',
  'ename' => 'content',
  'cname' => 'ÄÚÈÝ',
  'chid' => '3',
  'issystem' => '0',
  'available' => '1',
  'isfunc' => '0',
  'func' => '',
  'innertext' => '',
  'fromcode' => '0',
  'length' => '0',
  'datatype' => 'htmltext',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>