<?php
$catalog22_0 = array (
  'caid' => '22',
  'sid' => '0',
  'level' => '0',
  'pid' => '0',
  'title' => 'Êé¿â',
  'vieworder' => '0',
  'trueorder' => '7',
  'chids' => '',
  'mchids' => '',
  'isframe' => '0',
  'dirname' => 'shuku',
  'smallsite' => '',
  'apmid' => '4',
  'crpmid' => '0',
  'rpmid' => '0',
  'dpmid' => '0',
  'allowsale' => '0',
  'allowfsale' => '0',
  'taxcp' => '',
  'awardcp' => '',
  'ftaxcp' => '',
  'customurl' => '',
  'clicks' => '0',
  'archives' => '0',
  'indextpl' => '',
  'listtpl' => '',
  'bktpl' => '',
) ;
?>