<?php
$mfields2_0 = array (
  'mname' => 
  array (
    'cname' => '用户名',
    'issystem' => '1',
    'available' => '1',
    'iscustom' => '0',
    'mcommon' => '1',
    'isfunc' => '0',
    'tbl' => 'main',
    'datatype' => 'text',
    'isadmin' => '0',
    'vieworder' => '0',
    'pmid' => '0',
    'useredit' => '0',
  ),
  'password' => 
  array (
    'cname' => '密码',
    'issystem' => '1',
    'available' => '1',
    'iscustom' => '0',
    'mcommon' => '1',
    'isfunc' => '0',
    'tbl' => 'main',
    'datatype' => 'text',
    'isadmin' => '0',
    'vieworder' => '0',
    'pmid' => '0',
    'useredit' => '0',
  ),
  'email' => 
  array (
    'cname' => 'Email',
    'issystem' => '1',
    'available' => '1',
    'iscustom' => '0',
    'mcommon' => '1',
    'isfunc' => '0',
    'tbl' => 'main',
    'datatype' => 'text',
    'isadmin' => '0',
    'vieworder' => '0',
    'pmid' => '0',
    'useredit' => '0',
  ),
  'nicename' => 
  array (
    'cname' => '笔名',
    'issystem' => '0',
    'available' => '1',
    'iscustom' => '1',
    'mcommon' => '1',
    'isfunc' => '0',
    'tbl' => 'sub',
    'datatype' => 'text',
    'isadmin' => '0',
    'vieworder' => '0',
    'pmid' => '0',
    'useredit' => '0',
  ),
  'gonggao' => 
  array (
    'cname' => '作者公告',
    'issystem' => '0',
    'available' => '1',
    'iscustom' => '1',
    'mcommon' => '0',
    'isfunc' => '0',
    'tbl' => 'custom',
    'datatype' => 'multitext',
    'isadmin' => '0',
    'vieworder' => '0',
    'pmid' => '0',
    'useredit' => '0',
  ),
) ;
?>