<?php
$ffield_7_xs_pai_0 = array (
  'fid' => '29',
  'ename' => 'xs_pai',
  'cname' => 'еепР',
  'chid' => '7',
  'issystem' => '0',
  'available' => '1',
  'isfunc' => '0',
  'func' => '',
  'innertext' => '',
  'fromcode' => '0',
  'length' => '10',
  'datatype' => 'text',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => 'number',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>