<?php
$mmnlangs_0 = array (
  'mmenutype_13' => '个人中心',
  'mmenuitem_3' => '我的主页',
  'mmenuitem_250' => '我的小说',
  'mmenuitem_18' => '我的书架',
  'mmenuitem_8' => '我的账户',
  'mmenuitem_20' => '我的书评',
  'mmenuitem_27' => '我的消息',
  'mmenuitem_1' => '我的资料',
  'mmenuitem_253' => '作者公告',
  'mmenuitem_32' => '成为作家',
  'mmenutype_4' => '我的消息',
  'mmenutype_2' => '内容管理',
  'mmenuitem_15' => '个人分类',
  'mmenutype_3' => '文档交互',
  'mmenuitem_114' => '我的举报',
  'mmenuitem_31' => '我的订阅',
  'mmenutype_9' => '空间交互',
  'mmenuitem_105' => '提交的回复',
  'mmenuitem_106' => '收到的回复',
  'mmenuitem_107' => '提交的评论',
  'mmenuitem_108' => '收到的评论',
  'mmenutype_8' => '我的账户',
  'mmenuitem_9' => '积分变更记录',
  'mmenutype_12' => '好友',
  'mmenuitem_238' => '我的好友',
  'mmenuitem_239' => '好友申请管理',
  'mmenutype_1' => '个人资料',
  'mmenuitem_5' => '成为VIP',
) ;
?>