<?php
$field_2_score_4_0 = array (
  'fid' => '69',
  'ename' => 'score_4',
  'cname' => 'score_4',
  'chid' => '2',
  'issystem' => '0',
  'iscustom' => '1',
  'mcommon' => '1',
  'isfunc' => '0',
  'func' => '',
  'available' => '0',
  'tbl' => 'main',
  'innertext' => '',
  'fromcode' => '0',
  'issearch' => '0',
  'length' => '0',
  'datatype' => 'int',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'istxt' => '0',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>