<?php
$mfield_1_nicename_0 = array (
  'mfid' => '14',
  'cname' => 'êÇ³Æ',
  'ename' => 'nicename',
  'mchid' => '1',
  'issystem' => '0',
  'available' => '1',
  'iscustom' => '1',
  'mcommon' => '1',
  'isfunc' => '0',
  'func' => '',
  'tbl' => 'sub',
  'innertext' => '',
  'fromcode' => '0',
  'issearch' => '0',
  'length' => '200',
  'datatype' => 'text',
  'notnull' => '0',
  'nohtml' => '1',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>