<?php
$catalog13_0 = array (
  'caid' => '13',
  'sid' => '0',
  'level' => '1',
  'pid' => '11',
  'title' => '自由专题',
  'vieworder' => '0',
  'trueorder' => '19',
  'chids' => '2',
  'mchids' => '',
  'isframe' => '0',
  'dirname' => 'zirou',
  'smallsite' => '',
  'apmid' => '4',
  'crpmid' => '0',
  'rpmid' => '0',
  'dpmid' => '0',
  'allowsale' => '0',
  'allowfsale' => '0',
  'taxcp' => '',
  'awardcp' => '',
  'ftaxcp' => '',
  'customurl' => '',
  'clicks' => '0',
  'archives' => '0',
  'indextpl' => '',
  'listtpl' => '',
  'bktpl' => '',
) ;
?>