<?php
$field_4_subtitle_0 = array (
  'fid' => '37',
  'ename' => 'subtitle',
  'cname' => 'ИББъЬт',
  'chid' => '4',
  'issystem' => '0',
  'iscustom' => '1',
  'mcommon' => '0',
  'isfunc' => '0',
  'func' => '',
  'available' => '0',
  'tbl' => 'custom',
  'innertext' => '',
  'fromcode' => '0',
  'issearch' => '0',
  'length' => '255',
  'datatype' => 'text',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '',
  'vdefault' => '',
  'istxt' => '0',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>