<?php
$cfields_0 = array (
  'title' => 
  array (
    'fid' => '1',
    'ename' => 'title',
    'cname' => '标题',
    'cu' => '4',
    'available' => '1',
    'isfunc' => '0',
    'func' => '',
    'isadmin' => '0',
    'innertext' => '',
    'fromcode' => '0',
    'length' => '80',
    'datatype' => 'text',
    'notnull' => '0',
    'nohtml' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'rpid' => '0',
    'vieworder' => '0',
    'mode' => '0',
    'guide' => '',
    'vdefault' => '',
    'pmid' => '0',
    'useredit' => '0',
  ),
  'content' => 
  array (
    'fid' => '2',
    'ename' => 'content',
    'cname' => '内容',
    'cu' => '4',
    'available' => '1',
    'isfunc' => '0',
    'func' => '',
    'isadmin' => '0',
    'innertext' => '',
    'fromcode' => '0',
    'length' => '0',
    'datatype' => 'multitext',
    'notnull' => '0',
    'nohtml' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'rpid' => '0',
    'vieworder' => '0',
    'mode' => '0',
    'guide' => '',
    'vdefault' => '',
    'pmid' => '0',
    'useredit' => '0',
  ),
  'score' => 
  array (
    'fid' => '3',
    'ename' => 'score',
    'cname' => '评分',
    'cu' => '4',
    'available' => '1',
    'isfunc' => '0',
    'func' => '',
    'isadmin' => '0',
    'innertext' => '1
2
3
4
5',
    'fromcode' => '0',
    'length' => '10',
    'datatype' => 'select',
    'notnull' => '0',
    'nohtml' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'rpid' => '0',
    'vieworder' => '0',
    'mode' => '0',
    'guide' => '',
    'vdefault' => '',
    'pmid' => '0',
    'useredit' => '0',
  ),
) ;
?>