<?php
$catalog24_0 = array (
  'caid' => '24',
  'sid' => '0',
  'level' => '0',
  'pid' => '0',
  'title' => 'п║к╣еепп╟Я',
  'vieworder' => '0',
  'trueorder' => '8',
  'chids' => '',
  'mchids' => '',
  'isframe' => '0',
  'dirname' => 'xiaoshuopaihangbang',
  'smallsite' => '',
  'apmid' => '4',
  'crpmid' => '0',
  'rpmid' => '0',
  'dpmid' => '0',
  'allowsale' => '0',
  'allowfsale' => '0',
  'taxcp' => '',
  'awardcp' => '',
  'ftaxcp' => '',
  'customurl' => '',
  'clicks' => '0',
  'archives' => '0',
  'indextpl' => 'panhanindex.html',
  'listtpl' => '',
  'bktpl' => '',
) ;
?>