<?php
$gmission20_0 = array (
  'gsid' => '20',
  'cname' => '单篇内容',
  'gmid' => '7',
  'sonid' => '0',
  'pid' => '0',
  'mcharset' => 'gbk',
  'timeout' => '5',
  'mcookies' => '',
  'umode' => '0',
  'uurls' => '',
  'uregular' => 'http://www.duwenzhang.com/wenzhang/xiaoyuanwenzhang/list_4_(*).html',
  'ufromnum' => '5',
  'utonum' => '6',
  'ufrompage' => '0',
  'udesc' => '0',
  'uinclude' => '',
  'uforbid' => '',
  'uregion' => '当前位置：(*)首页',
  'uspilit' => '<table width="100%" border="0" cellspacing="0" cellpadding="0" class="tbspan" style="margin-top:6px">',
  'uurltag' => '<a href="(*)"',
  'utitletag' => 'class="ulink">(*)</a>',
  'uurltag1' => '',
  'uinclude1' => '',
  'uforbid1' => '',
  'uurltag2' => '',
  'uinclude2' => '',
  'uforbid2' => '',
  'mpfield' => '',
  'mpmode' => '0',
  'mptag' => '',
  'mpinclude' => '',
  'mpforbid' => '',
  'fsettings' => 
  array (
    'subject' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '<h1>(*)</h1>',
      'fromreplace' => '',
      'toreplace' => '',
      'rpid' => '0',
      'jumpfile' => '',
      'clearhtml' => '',
    ),
    'author' => 
    array (
      'frompage' => '1',
      'func' => '',
      'ftag' => '',
      'fromreplace' => '',
      'toreplace' => '',
      'rpid' => '0',
      'jumpfile' => '',
      'clearhtml' => '',
    ),
    'content' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '<div id="wenzhangziti" class="article 10543">(*)</div>',
      'fromreplace' => '<IMG(*)>',
      'toreplace' => '',
      'rpid' => '0',
      'jumpfile' => '',
      'clearhtml' => '1,3,4,5,6,7,8,9,10,11,13',
    ),
  ),
  'dvalues' => 
  array (
    'musts' => 'subject',
    'autoabstract' => '1',
    'autothumb' => '0',
    'caid' => '10',
    'subtitle' => '',
    'source' => '',
    'keywords' => '',
    'ccid1' => '0',
    'ccid2' => '0',
    'ccid3' => '0',
    'ccid4' => '0',
    'ccid5' => '0',
    'ccid7' => '0',
    'ccid6' => '0',
  ),
  'sid' => '0',
) ;
?>