<?php
$ffield_6_xiaoshuo_name_0 = array (
  'fid' => '23',
  'ename' => 'xiaoshuo_name',
  'cname' => '小说名称',
  'chid' => '6',
  'issystem' => '0',
  'available' => '1',
  'isfunc' => '0',
  'func' => '',
  'innertext' => '',
  'fromcode' => '0',
  'length' => '255',
  'datatype' => 'text',
  'notnull' => '1',
  'nohtml' => '1',
  'mlimit' => '',
  'regular' => '',
  'min' => '2',
  'max' => '255',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '请输入推荐的小说名称',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>