<?php
$crprices_0 = array (
  '1_1' => 
  array (
    'cpid' => '1',
    'ename' => '1_1',
    'cname' => '1积分',
    'crid' => '1',
    'crvalue' => '1',
    'available' => '0',
    'tax' => '1',
    'award' => '1',
    'sale' => '1',
    'ftax' => '0',
    'fsale' => '1',
  ),
  '1_2' => 
  array (
    'cpid' => '2',
    'ename' => '1_2',
    'cname' => '2积分',
    'crid' => '1',
    'crvalue' => '2',
    'available' => '0',
    'tax' => '1',
    'award' => '1',
    'sale' => '1',
    'ftax' => '0',
    'fsale' => '1',
  ),
  '2_1' => 
  array (
    'cpid' => '3',
    'ename' => '2_1',
    'cname' => '1经典币',
    'crid' => '2',
    'crvalue' => '1',
    'available' => '0',
    'tax' => '1',
    'award' => '1',
    'sale' => '1',
    'ftax' => '0',
    'fsale' => '1',
  ),
  '2_2' => 
  array (
    'cpid' => '4',
    'ename' => '2_2',
    'cname' => '2经典币',
    'crid' => '2',
    'crvalue' => '2',
    'available' => '0',
    'tax' => '1',
    'award' => '1',
    'sale' => '1',
    'ftax' => '0',
    'fsale' => '1',
  ),
  '2_3' => 
  array (
    'cpid' => '5',
    'ename' => '2_3',
    'cname' => '3经典币',
    'crid' => '2',
    'crvalue' => '3',
    'available' => '0',
    'tax' => '1',
    'award' => '0',
    'sale' => '1',
    'ftax' => '0',
    'fsale' => '0',
  ),
  '2_4' => 
  array (
    'cpid' => '6',
    'ename' => '2_4',
    'cname' => '4经典币',
    'crid' => '2',
    'crvalue' => '4',
    'available' => '0',
    'tax' => '1',
    'award' => '0',
    'sale' => '1',
    'ftax' => '0',
    'fsale' => '0',
  ),
  '2_5' => 
  array (
    'cpid' => '7',
    'ename' => '2_5',
    'cname' => '5经典币',
    'crid' => '2',
    'crvalue' => '5',
    'available' => '0',
    'tax' => '1',
    'award' => '0',
    'sale' => '1',
    'ftax' => '0',
    'fsale' => '0',
  ),
) ;
?>