<?php
$field_6_subject_0 = array (
  'fid' => '78',
  'ename' => 'subject',
  'cname' => 'БъЬт',
  'chid' => '6',
  'issystem' => '1',
  'iscustom' => '0',
  'mcommon' => '1',
  'isfunc' => '0',
  'func' => '',
  'available' => '1',
  'tbl' => 'main',
  'innertext' => '',
  'fromcode' => '0',
  'issearch' => '0',
  'length' => '50',
  'datatype' => 'text',
  'notnull' => '1',
  'nohtml' => '1',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '1',
  'guide' => '',
  'vdefault' => '',
  'istxt' => '0',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>