<?php
$field_5_tipimg_0 = array (
  'fid' => '47',
  'ename' => 'tipimg',
  'cname' => '头部图片',
  'chid' => '5',
  'issystem' => '0',
  'iscustom' => '1',
  'mcommon' => '0',
  'isfunc' => '0',
  'func' => '',
  'available' => '1',
  'tbl' => 'custom',
  'innertext' => '',
  'fromcode' => '0',
  'issearch' => '0',
  'length' => '0',
  'datatype' => 'image',
  'notnull' => '0',
  'nohtml' => '0',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '0',
  'guide' => '图片像素宽度最佳为950px',
  'vdefault' => '',
  'istxt' => '0',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>