<?php
$ffield_8_xs_miaoshu_0 = array (
  'fid' => '32',
  'ename' => 'xs_miaoshu',
  'cname' => 'ะกหตร่ส๖',
  'chid' => '8',
  'issystem' => '0',
  'available' => '1',
  'isfunc' => '0',
  'func' => '',
  'innertext' => '',
  'fromcode' => '0',
  'length' => '255',
  'datatype' => 'text',
  'notnull' => '1',
  'nohtml' => '1',
  'mlimit' => '',
  'regular' => '',
  'min' => '',
  'max' => '',
  'rpid' => '0',
  'isadmin' => '0',
  'vieworder' => '0',
  'mode' => '1',
  'guide' => '',
  'vdefault' => '',
  'pmid' => '0',
  'useredit' => '0',
) ;
?>