<?php
$gmission26_0 = array (
  'gsid' => '26',
  'cname' => '清风玄幻章节',
  'gmid' => '4',
  'sonid' => '0',
  'pid' => '25',
  'mcharset' => 'gbk',
  'timeout' => '5',
  'mcookies' => '',
  'umode' => '0',
  'uurls' => '',
  'uregular' => '',
  'ufromnum' => '0',
  'utonum' => '0',
  'ufrompage' => '1',
  'udesc' => '0',
  'uinclude' => '',
  'uforbid' => '',
  'uregion' => '<div id="BookText">(*)<script(?)></SCRIPT>',
  'uspilit' => '<li>',
  'uurltag' => '<a href="(*)">',
  'utitletag' => '">(*)</a>',
  'uurltag1' => '',
  'uinclude1' => '',
  'uforbid1' => '',
  'uurltag2' => '',
  'uinclude2' => '',
  'uforbid2' => '',
  'mpfield' => '',
  'mpmode' => '0',
  'mptag' => '',
  'mpinclude' => '',
  'mpforbid' => '',
  'fsettings' => 
  array (
    'subject' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '<div id="Title"><h1><a href="(?)">(?)</a>(*)</h1>',
      'fromreplace' => '',
      'toreplace' => '',
      'rpid' => '0',
      'jumpfile' => '',
      'clearhtml' => '12',
    ),
    'content' => 
    array (
      'frompage' => '0',
      'func' => '',
      'ftag' => '<div class="content" >(*)<div id="footbar">',
      'fromreplace' => 'http://www.qingfo.com/(|)<script(*)</script>(|)</div>(|)<div(*)>(|)<font(*)</font>(|)清风(|)<iframe(*)</iframe>',
      'toreplace' => '(|)(|)(|)(|)(|)(|)',
      'rpid' => '1',
      'jumpfile' => '',
      'clearhtml' => '1,4,5,7,8,13',
    ),
  ),
  'dvalues' => 
  array (
    'musts' => 'subject',
    'autoabstract' => '1',
    'autothumb' => '0',
    'caid' => '4',
    'author' => '',
    'source' => '',
    'keywords' => '',
    'ccid1' => '0',
    'ccid2' => '0',
    'ccid3' => '0',
    'ccid4' => '0',
    'ccid5' => '0',
    'ccid7' => '0',
    'ccid6' => '0',
  ),
  'sid' => '0',
) ;
?>